"""empty message

Revision ID: 382f68685766
Revises: 1596cd18fd4e
Create Date: 2024-05-18 08:28:36.529480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382f68685766'
down_revision = '1596cd18fd4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user1_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user2_id', sa.Integer(), nullable=False))
        batch_op.alter_column('match_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['match_id'])
        batch_op.create_foreign_key(None, 'musync_user', ['user2_id'], ['user_id'])
        batch_op.create_foreign_key(None, 'musync_user', ['user1_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('match_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('user2_id')
        batch_op.drop_column('user1_id')

    # ### end Alembic commands ###
