"""empty message

Revision ID: 40f4b8421d53
Revises: 729c87d876ab
Create Date: 2024-04-24 13:28:23.309727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f4b8421d53'
down_revision = '729c87d876ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('top_listened_artist', schema=None) as batch_op:
        batch_op.drop_constraint('top_listened_artist_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('top_listened_music', schema=None) as batch_op:
        batch_op.drop_constraint('top_listened_music_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('top_listened_music', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('top_listened_music_user_id_fkey', 'user_music_statistic', ['user_id'], ['user_id'])

    with op.batch_alter_table('top_listened_artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('top_listened_artist_user_id_fkey', 'user_music_statistic', ['user_id'], ['user_id'])

    # ### end Alembic commands ###
