"""empty message

Revision ID: 51d058fdcad3
Revises: ce9f74acf21e
Create Date: 2024-04-24 12:26:02.860813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51d058fdcad3'
down_revision = 'ce9f74acf21e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('top_listened_artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('top_listened_artist',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('top_listened_music', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('top_listened_music',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('user_music_statistic', schema=None) as batch_op:
        batch_op.drop_column('top_listened_music')
        batch_op.drop_column('top_listened_artist')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_music_statistic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('top_listened_artist', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('top_listened_music', sa.VARCHAR(), autoincrement=False, nullable=True))

    with op.batch_alter_table('top_listened_music', schema=None) as batch_op:
        batch_op.alter_column('top_listened_music',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('id')

    with op.batch_alter_table('top_listened_artist', schema=None) as batch_op:
        batch_op.alter_column('top_listened_artist',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###
