"""empty message

Revision ID: 555766a2e55e
Revises: 5c7b45834591
Create Date: 2024-05-18 08:16:44.914160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555766a2e55e'
down_revision = '5c7b45834591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['match_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
