"""empty message

Revision ID: 729c87d876ab
Revises: cb55443808b7
Create Date: 2024-04-24 13:06:13.248557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '729c87d876ab'
down_revision = 'cb55443808b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('top_listened_artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user_music_statistic', ['user_id'], ['user_id'])

    with op.batch_alter_table('top_listened_music', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user_music_statistic', ['user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('top_listened_music', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('top_listened_artist', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
