"""empty message

Revision ID: b21b9b0af28c
Revises: e87230b021bf
Create Date: 2024-04-06 08:00:24.078138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b21b9b0af28c'
down_revision = 'e87230b021bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('score_user1', sa.Integer(), nullable=True),
    sa.Column('score_user2', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('match_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###
