"""empty message

Revision ID: ce9f74acf21e
Revises: 1b7121f16981
Create Date: 2024-04-06 09:51:04.645625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce9f74acf21e'
down_revision = '1b7121f16981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('musync_user', schema=None) as batch_op:
        batch_op.drop_constraint('musync_user_gender_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('musync_user', schema=None) as batch_op:
        batch_op.create_unique_constraint('musync_user_gender_key', ['gender'])

    # ### end Alembic commands ###
