version: "3.0.2"

services:

  flask:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    command: bash -c "python3 init_db.py && flask --app main run --port 5000 --host=0.0.0.0"
    environment:
      FLASK_APP: init_db.py
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - database
    volumes:
      - ./app/migrations:/app/migrations

  database:
    image: postgres:alpine3.19
    container_name: database_relationship_management
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432"

volumes:
  migrations: