version: "3.0.2"

services:

  flask:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    command: bash -c "python3 init_db.py && flask db upgrade && flask --app main run --port 5000 --host=0.0.0.0"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      FLASK_DEBUG: true
      FLASK_APP: init_db.py
      FLASK_ENV: development
    depends_on:
      database:
        condition: service_healthy
        restart: true
    volumes:
      - ./app/migrations:/app/migrations
      - ./app:/app

  database:
    image: postgres:alpine3.19
    container_name: database_relationship_management
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432"
    healthcheck:
      test: [ "CMD", 'psql', '-U', "tech", 'main' ]
      timeout: 2s
      retries: 5

volumes:
  migrations:
  app: